package dji.sdk.api.MainController;

public class DJIMainControllerTypeDef {

	public enum DJIMCUErrorType {
		MCU_COMPASS_CALIBRATION_ERROR,
		MCU_COMPASS_ERROR,
		MCU_CONFIG_ERROR,
		MCU_IMU_CALIBRATION_ERROR,
		MCU_IMU_ERROR,
		MCU_INVALID_BATTERY_COMMUNICATION_ERROR,
		MCU_INVALID_BATTERY_ERROR,
		MCU_NO_ERROR,
		MCU_PMU_ERROR,
		MCU_SENSOR_ERROR,
		MCU_SERIALNUM_ERROR,
		MCU_TRANSMITTER_CALIBRATION_ERROR,
		MCU_TRANSMITTER_ERROR,
		MCU_UNKOWN_ERROR,
		MCU_X1_ERROR,
		MCU_X2_ERROR;
	}

	public enum DJIPhantomType {
		DJIPhantom2Vision,
		DJIPhantom2VisionPlus,
		Unknown;
	}
	
}
